name: "coverage"
on:
  pull_request:
    branches:
      - main
jobs:
  type-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: borales/actions-yarn@v4
        name: Install
        with:
          cmd: install
      - uses: borales/actions-yarn@v4
        name: Type Check
        with:
          cmd: typeCheck
  test-shared:
    runs-on: ubuntu-latest
    needs: type-check
    steps:
      - uses: actions/checkout@v3
      - run: npx yarn
      - uses: ArtiomTr/jest-coverage-report-action@v2
        name: Test Shared
        with:
          skip-step: install
          test-script: yarn test
          working-directory: ./packages/nlp-manager-shared
          output: comment, report-markdown
  test-ui:
    runs-on: ubuntu-latest
    needs: type-check
    steps:
      - uses: actions/checkout@v3
      - run: npx yarn
      - uses: ArtiomTr/jest-coverage-report-action@v2
        name: Test UI
        with:
          skip-step: install
          test-script: yarn test
          working-directory: ./packages/nlp-manager-ui
          output: comment, report-markdown
  test-electron:
    runs-on: ubuntu-latest
    needs: type-check
    steps:
      - uses: actions/checkout@v3
      - run: npx yarn
      - uses: ArtiomTr/jest-coverage-report-action@v2
        name: Test Electron
        with:
          skip-step: install
          test-script: yarn test
          working-directory: ./packages/nlp-manager-electron
          output: comment, report-markdown
